set(SourceFiles
    Source/ARA/Objects/ARA_AudioSource.cpp
    Source/ARA/Objects/ARA_AudioSource.h
    Source/ARA/Objects/ARA_DocumentController.cpp
    Source/ARA/Objects/ARA_DocumentController.h
    Source/ARA/Objects/ARA_PlaybackRegion.cpp
    Source/ARA/Objects/ARA_PlaybackRegion.h
    Source/ARA/Objects/ARA_PlaybackRenderer.cpp
    Source/ARA/Objects/ARA_PlaybackRenderer.h
    Source/ARA/Views/PlaybackRegionView.cpp
    Source/ARA/Views/PlaybackRegionView.h
    Source/EditorState.h
    Source/MainView/MainView.cpp
    Source/MainView/MainView.h
    Source/PluginEditor.cpp
    Source/PluginEditor.h
    Source/PluginProcessor.cpp
    Source/PluginProcessor.h
    Source/Sections/InspectSection.cpp
    Source/Sections/InspectSection.h
    Source/Sections/NavigationSection.cpp
    Source/Sections/NavigationSection.h
    Source/Sections/TimelineSection.cpp
    Source/Sections/TimelineSection.h
    Source/TestTimeline/Test_AudioModification.cpp
    Source/TestTimeline/Test_AudioModification.h
    Source/TestTimeline/Test_AudioSource.cpp
    Source/TestTimeline/Test_AudioSource.h
    Source/TestTimeline/Test_Document.h
    Source/TestTimeline/Test_DocumentController.cpp
    Source/TestTimeline/Test_DocumentController.h
    Source/TestTimeline/Test_PlaybackRegion.cpp
    Source/TestTimeline/Test_PlaybackRegion.h
    Source/TestTimeline/Test_PlaybackRenderer.cpp
    Source/TestTimeline/Test_PlaybackRenderer.h
    Source/TestUtils/TestUtils.cpp
    Source/TestUtils/TestUtils.h
    Source/Timeline/Objects/Timeline_AudioModification.cpp
    Source/Timeline/Objects/Timeline_AudioModification.h
    Source/Timeline/Objects/Timeline_AudioProcessor/Timeline_ModificationProcessor.cpp
    Source/Timeline/Objects/Timeline_AudioProcessor/Timeline_ModificationProcessor.h
    Source/Timeline/Objects/Timeline_AudioProcessor/Timeline_UndoAction.cpp
    Source/Timeline/Objects/Timeline_AudioProcessor/Timeline_UndoAction.h
    Source/Timeline/Objects/Timeline_AudioSource.cpp
    Source/Timeline/Objects/Timeline_AudioSource.h
    Source/Timeline/Objects/Timeline_Document.cpp
    Source/Timeline/Objects/Timeline_Document.h
    Source/Timeline/Objects/Timeline_DocumentController.cpp
    Source/Timeline/Objects/Timeline_DocumentController.h
    Source/Timeline/Objects/Timeline_PlaybackRegion.cpp
    Source/Timeline/Objects/Timeline_PlaybackRegion.h
    Source/Timeline/Objects/Timeline_PlaybackRenderer.cpp
    Source/Timeline/Objects/Timeline_PlaybackRenderer.h
    Source/Timeline/Objects/Timeline_RegionSequence.cpp
    Source/Timeline/Objects/Timeline_RegionSequence.h
    Source/Timeline/Objects/Timeline_Renderer.cpp
    Source/Timeline/Objects/Timeline_Renderer.h
    Source/Timeline/Sections/DocumentSection.cpp
    Source/Timeline/Sections/DocumentSection.h
    Source/Timeline/Sections/SequenceHeadersSection.cpp
    Source/Timeline/Sections/SequenceHeadersSection.h
    Source/Timeline/Sections/TimeRulerSection.cpp
    Source/Timeline/Sections/TimeRulerSection.h
    Source/Timeline/Sections/ZoomControlsSection.cpp
    Source/Timeline/Sections/ZoomControlsSection.h
    Source/Timeline/Views/DocumentView.cpp
    Source/Timeline/Views/DocumentView.h
    Source/Timeline/Views/PlaybackRegionView.cpp
    Source/Timeline/Views/PlaybackRegionView.h
    Source/Timeline/Views/RegionSequenceView.cpp
    Source/Timeline/Views/RegionSequenceView.h
    Source/Timeline/Views/SequenceHeaderView.cpp
    Source/Timeline/Views/SequenceHeaderView.h
    Source/Timeline/Views/TimeRulerView.cpp
    Source/Timeline/Views/TimeRulerView.h
    Source/Timeline/ZoomState/ZoomState.cpp
    Source/Timeline/ZoomState/ZoomState.h
    Source/Timeline/ZoomState/ZoomStateListener.h
    Source/Timeline/widgets/SequenceHeader.cpp
    Source/Timeline/widgets/SequenceHeader.h
    Source/Timeline/widgets/TimeRuler.cpp
    Source/Timeline/widgets/TimeRuler.h
    Source/Timeline/widgets/ZoomControls.h
    Source/Util/Colors.h
    Source/Util/Juce_Header.h
    Source/WaveCache/WaveformCache.cpp
    Source/WaveCache/WaveformCache.h
)